"""
catbird-mls Python bindings.

Generated via UniFFI from the catbird-mls Rust crate.
Provides MLS (Messaging Layer Security) group chat functionality.

Usage:
    from catbird_mls import CatbirdMls
"""
# The actual bindings are generated by UniFFI into this package
